Packer base
Otus-DevOps-2018-02/ivanov2103_infra pull request #6
Opened 2018-04-03 18:05 UTC by ivanov2103

# Выполнено ДЗ № 06  
- [x] Основное ДЗ  
- [x] Задание со *  

## В процессе сделано:  
- Was created Packer template for GCP image "Base" (Ruby, MongoDB).  
- Was created Packer template for GCP image "Full" (Ruby, MongoDB, deployed application with autostart).  
- Was created instatnce from GCP template "Full" by gcloud command.  
testapp_IP = 35.195.95.117  
testapp_port = 9292  

## Как запустить проект:  
- Run command: **packer build -var-file=variables.json immutable.json ; sleep.exe 20 ; ../config-scripts/create-reddit-vm.sh**.  

## Как проверить работоспособность:  
- http://35.195.95.117:9292/ must be accessible.  

## PR checklisk  
- [x] Выставил label с номером домашнего задания  
- [x] Выставил label с темой домашнего задания

2018-04-06 09:21 UTC, Nklya requested changes
Добрый день.

Игорь, почти все выглядит ок.
Нужно только разобраться с packer/variables.json и .gitignore.

2018-04-06 09:21 UTC, Nklya commented on packer/variables.json
> +{
packer/variables.json должны быть в .gitignore и отсюда вычищены

2018-04-06 09:21 UTC, Nklya commented on packer/immutable.json
> +    "source_image_family": "{{user `source_img`}}",
Здесь в качестве базового образа можно было использовать  reddit-base, тогда не надо будет повторно ставить монгу с руби.

2018-04-06 09:21 UTC, Nklya commented on packer/files/to_systemd.sh
> +#!/bin/bash
Да, удобно.

2018-04-06 09:21 UTC, Nklya commented on .gitignore
> +./packer/variables.json
Можно просто `variables.json` или `packer/variables.json`

2018-04-11 16:18 UTC, ivanov2103 commented on packer/variables.json
> +{
Поправил, почитал про формат .gitignore внимательнее

2018-04-11 16:20 UTC, Nklya commented on packer/variables.json
> +{
Сам файл тоже надо было удалить

2018-04-11 16:21 UTC, Nklya approved these changes
Теперь все выглядит ок 👍

2018-04-11 16:21 UTC, ivanov2103 commented on packer/immutable.json
> +    "source_image_family": "{{user `source_img`}}",
Делал самодостаточные шаблоны. Не предполагал, что понадобиться базовый в следующем Д..З.

2018-04-11 16:22 UTC, Nklya commented on packer/immutable.json
> +    "source_image_family": "{{user `source_img`}}",
Это не то, чтобы нужно.
Просто на этом примере можно рассмотреть пример переиспользования.

2018-04-11 16:23 UTC, merged